// Player & Tester Database for Jordanian MCTiers
// This file is auto-generated by the Admin Panel. Do not edit manually.

const INITIAL_PLAYERS = [
  {
    "username": "DEATHN0TE_",
    "nickname": "",
    "city": "Amman",
    "badges": [],
    "socials": {
      "discord": "",
      "youtube": ""
    },
    "tiers": {
      "spear_mace": "HT2",
      "vanilla": "LT4",
      "uhc": "LT5",
      "pot": "LT5",
      "nethop": "LT5",
      "smp": "HT5",
      "sword": "HT5",
      "axe": "HT5",
      "mace": "LT4",
      "overall": "HT4"
    },
    "history": [
      {
        "date": "2026-07-20",
        "gamemode": "Spear/Mace",
        "change": "HT4 → HT2",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Axe",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Sword",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "SMP",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "NethOP",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Pot",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "UHC",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-19",
        "gamemode": "Vanilla",
        "change": "None → LT4",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-19",
        "gamemode": "Overall",
        "change": "None → Registered",
        "note": "Added with: Spear/Mace: HT4, Mace: LT4"
      }
    ]
  },
  {
    "username": "SK_YX",
    "nickname": "",
    "city": "Amman",
    "badges": [],
    "socials": {
      "discord": "",
      "youtube": ""
    },
    "tiers": {
      "spear_mace": "LT4",
      "vanilla": "LT5",
      "uhc": "LT5",
      "pot": "LT5",
      "nethop": "LT5",
      "smp": "HT5",
      "sword": "LT4",
      "axe": "HT5",
      "mace": "HT5",
      "overall": "HT5"
    },
    "history": [
      {
        "date": "2026-07-20",
        "gamemode": "Axe",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "SMP",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "NethOP",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Pot",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "UHC",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Vanilla",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-19",
        "gamemode": "Sword",
        "change": "HT1 → LT4",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-19",
        "gamemode": "Sword",
        "change": "None → HT1",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-19",
        "gamemode": "Overall",
        "change": "None → Registered",
        "note": "Added with: Spear/Mace: LT4, Mace: HT5"
      }
    ]
  },
  {
    "username": "NOT_KALSHER",
    "nickname": "",
    "city": "Amman",
    "badges": [],
    "socials": {
      "discord": "",
      "youtube": ""
    },
    "tiers": {
      "spear_mace": "LT5",
      "vanilla": "HT5",
      "uhc": "HT1",
      "pot": "HT5",
      "nethop": "LT4",
      "smp": "HT5",
      "sword": "None",
      "axe": "LT5",
      "mace": "LT5",
      "overall": "LT3"
    },
    "history": [
      {
        "date": "2026-07-20",
        "gamemode": "UHC",
        "change": "HT5 → HT1",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Axe",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "SMP",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "NethOP",
        "change": "None → LT4",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Pot",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-19",
        "gamemode": "Overall",
        "change": "None → Registered",
        "note": "Added with: Spear/Mace: LT5, Vanilla: HT5, UHC: HT5, Mace: LT5"
      }
    ]
  },
  {
    "username": "Torch7007",
    "nickname": "",
    "city": "Zarqa",
    "badges": [],
    "socials": {
      "discord": "",
      "youtube": ""
    },
    "tiers": {
      "spear_mace": "HT5",
      "vanilla": "LT5",
      "uhc": "HT5",
      "pot": "LT5",
      "nethop": "HT5",
      "smp": "HT5",
      "sword": "LT4",
      "axe": "LT3",
      "mace": "HT5",
      "overall": "LT4"
    },
    "history": [
      {
        "date": "2026-07-20",
        "gamemode": "Mace",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Sword",
        "change": "None → LT4",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "SMP",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "NethOP",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Pot",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "UHC",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Vanilla",
        "change": "None → LT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-20",
        "gamemode": "Spear/Mace",
        "change": "None → HT5",
        "note": "Tier updated via database manager"
      },
      {
        "date": "2026-07-19",
        "gamemode": "Overall",
        "change": "None → Registered",
        "note": "Added with: Axe: LT3"
      }
    ]
  },
  {
    "username": "GR4VESS",
    "nickname": "",
    "city": "Amman",
    "badges": [],
    "socials": {
      "discord": "",
      "youtube": ""
    },
    "tiers": {
      "spear_mace": "LT5",
      "vanilla": "LT5",
      "uhc": "LT5",
      "pot": "LT5",
      "nethop": "LT5",
      "smp": "LT5",
      "sword": "LT5",
      "axe": "LT5",
      "mace": "LT5",
      "overall": "HT5"
    },
    "history": [
      {
        "date": "2026-07-20",
        "gamemode": "Overall",
        "change": "None → Registered",
        "note": "Added with: Spear/Mace: LT5, Vanilla: LT5, UHC: LT5, Pot: LT5, NethOP: LT5, SMP: LT5, Sword: LT5, Axe: LT5, Mace: LT5"
      }
    ]
  },
  {
    "username": "ryze5429",
    "nickname": "",
    "city": "Amman",
    "badges": [],
    "socials": {
      "discord": "",
      "youtube": ""
    },
    "tiers": {
      "spear_mace": "None",
      "vanilla": "None",
      "uhc": "None",
      "pot": "None",
      "nethop": "None",
      "smp": "None",
      "sword": "None",
      "axe": "None",
      "mace": "LT4",
      "overall": "LT5"
    },
    "history": [
      {
        "date": "2026-07-20",
        "gamemode": "Overall",
        "change": "None → Registered",
        "note": "Added with: Mace: LT4"
      }
    ]
  },
  {
    "username": "rghiq",
    "nickname": "",
    "city": "Amman",
    "badges": [],
    "socials": {
      "discord": "",
      "youtube": ""
    },
    "tiers": {
      "spear_mace": "LT5",
      "vanilla": "LT5",
      "uhc": "LT5",
      "pot": "LT5",
      "nethop": "LT5",
      "smp": "LT5",
      "sword": "LT5",
      "axe": "LT5",
      "mace": "HT5",
      "overall": "HT5"
    },
    "history": [
      {
        "date": "2026-07-22",
        "gamemode": "Overall",
        "change": "None → Registered",
        "note": "Added with: Spear/Mace: LT5, Vanilla: LT5, UHC: LT5, Pot: LT5, NethOP: LT5, SMP: LT5, Sword: LT5, Axe: LT5, Mace: HT5"
      }
    ]
  }
];

const INITIAL_TESTERS = [
  {
    "name": "sk_yx",
    "role": "mace tester",
    "gamemodes": [
      "Mace"
    ],
    "avatar": "sk_yx",
    "online": false
  }
];
